<h4> POSTTEST 7 KB </h4>
<h4> Muhammad Faisal Setiawan </h4>

<h2> input library yang digunakan pada posttest kali ini </h2>

In [20]:
import tensorflow as tf
import numpy as np

<h2> membuat random tensor shape 5.5 </h2>

In [21]:
random_tensor = tf.random.normal([5, 5], mean=0, stddev=1, seed=1).numpy()
random_tensor

array([[-0.28433853,  0.8922832 ,  0.8983451 ,  0.7163981 ,  0.34969485],
       [-0.37960768,  0.01531979,  0.27423722, -2.214901  , -0.08514621],
       [ 1.0113182 ,  0.6616626 ,  1.383323  , -0.40465203,  0.86142987],
       [-0.12589967, -1.418615  ,  2.0295074 ,  0.15304402,  0.13658497],
       [-0.49787143,  0.38847125, -0.4244715 ,  0.46214256, -0.5444318 ]],
      dtype=float32)

<h2> membuat variable prima tensor shape 5.5 </h2>

In [22]:
prima_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5, 5], dtype=tf.float32)
prima_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

<h2> Aritmatika pertambahan (add) </h2>

In [23]:
print("Hasil  pertambahan =",tf.add(random_tensor,prima_tensor).numpy())

Hasil  pertambahan = [[  1.7156615   3.8922832   5.898345    7.7163982  11.349695 ]
 [ 12.620392   17.01532    19.274237   20.785099   28.914854 ]
 [ 32.01132    37.661663   42.383324   42.59535    47.86143  ]
 [ 52.8741     57.581387   63.029507   71.153046   73.13658  ]
 [ 78.50213    83.38847    88.57553    97.46214   100.45557  ]]


<h2> Aritmatika pengurangan (subtract) </h2>

In [24]:
print("Hasil pengurangan =",tf.subtract(random_tensor, prima_tensor).numpy())

Hasil pengurangan = [[  -2.2843385   -2.1077168   -4.101655    -6.2836018  -10.650305 ]
 [ -13.379608   -16.98468    -18.725763   -25.214901   -29.085146 ]
 [ -29.988682   -36.338337   -39.616676   -43.40465    -46.13857  ]
 [ -53.1259     -60.418613   -58.970493   -70.846954   -72.86342  ]
 [ -79.49787    -82.61153    -89.42447    -96.53786   -101.54443  ]]


<h2> Aritmatika perkalian (multiply) </h2>

In [25]:
print("hasil perkalian =",tf.multiply(random_tensor, prima_tensor).numpy())

hasil perkalian = [[ -0.56867707   2.6768496    4.4917254    5.0147867    3.8466434 ]
 [ -4.9349       0.2604365    5.210507   -50.942722    -2.4692402 ]
 [ 31.350864    24.481516    56.71624    -17.400038    40.487206  ]
 [ -6.672683   -83.69828    123.79995     10.866125     9.970702  ]
 [-39.331844    32.243114   -37.77796     44.827827   -54.987614  ]]


<h2> Aritmatika pembagian (divide) </h2>

In [26]:
print("hasil pembagian =",tf.divide (random_tensor, prima_tensor).numpy())

hasil pembagian = [[-0.14216927  0.29742774  0.17966902  0.10234259  0.03179044]
 [-0.02920059  0.00090116  0.01443354 -0.09630004 -0.00293608]
 [ 0.03262317  0.01788277  0.03373959 -0.00941051  0.0183283 ]
 [-0.00237547 -0.02404432  0.03327061  0.00215555  0.00187103]
 [-0.00630217  0.00468038 -0.00476934  0.00476436 -0.00539041]]


<h2> Aritmatika logaritma (math.log) </h2>

In [27]:
print("hasil logaritma math.log =", tf.math.log (random_tensor, prima_tensor).numpy())

hasil logaritma math.log = [[        nan -0.1139717  -0.10720097 -0.33351925 -1.0506945 ]
 [        nan -4.1786094  -1.2937618          nan         nan]
 [ 0.01125463 -0.41299957  0.32448855         nan -0.14916162]
 [        nan         nan  0.7077931  -1.8770298  -1.9908084 ]
 [        nan -0.94553614         nan -0.7718819          nan]]


<h2> Aritmatika pangkat (pow) </h2>

In [28]:
print("hasil pangkat=", tf.pow(random_tensor, prima_tensor).numpy())

hasil pangkat= [[ 8.0848403e-02  7.1040851e-01  5.8508104e-01  9.6845858e-02
   9.5627229e-06]
 [-3.3990286e-06  1.4102624e-31  2.1105780e-11 -8.7730216e+07
  -9.4361422e-32]
 [ 1.4174985e+00  2.3096874e-07  5.9960731e+05 -1.2720790e-17
   9.0227008e-04]
 [-0.0000000e+00 -9.1202765e+08  5.6341576e+18  0.0000000e+00
   0.0000000e+00]
 [-1.1810252e-24  8.2563274e-35 -7.5599596e-34  3.0427649e-33
  -2.1394018e-27]]


<h2> Nilai Maksimal random tensor </h2>

In [29]:
print("Nilai Max =", tf.argmax(random_tensor, axis=0).numpy())

Nilai Max = [2 0 3 0 2]


<h2> Nilai Minimal random tensor </h2>

In [30]:
print("Nilai Min =",tf.argmin(random_tensor, axis=0).numpy())

Nilai Min = [4 3 4 1 4]


<h2> Penggabungan variable </h2>

In [31]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
prima_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5, 5], dtype=tf.float32)
print("size original data:",random_tensor.shape,prima_tensor.shape)
concated_tensor = tf.concat([random_tensor,prima_tensor],axis=0)
print("size concatenated data:",concated_tensor.shape)

size original data: (5, 5) (5, 5)
size concatenated data: (10, 5)


<h2> Desscending </h2>

In [32]:
print("existing prime tensor data:",prima_tensor.numpy())
sorted_random = tf.sort(random_tensor, direction = "DESCENDING")
print("random tensor sorted by descending order:",sorted_random.numpy())
sorted_prime = tf.sort(prima_tensor, direction = "DESCENDING")
print("prime tensor sorted by descending order:",sorted_prime.numpy())

existing prime tensor data: [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]
random tensor sorted by descending order: [[ 0.9124507   0.6950061   0.61860144 -0.3744468  -0.6192134 ]
 [ 0.6676718   0.4242158  -0.1350087  -0.17951003 -0.37561563]
 [ 1.4505777   1.1854254   0.34320396 -0.27241856 -0.31347093]
 [ 0.6069386  -0.29796734 -0.8780423  -1.4060947  -1.4172324 ]
 [ 0.37089893 -0.4037651  -0.7477049  -1.0725715  -1.1893758 ]]
prime tensor sorted by descending order: [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]]
